USE restaurant_management;

CREATE TABLE customers (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) NOT NULL,
  name VARCHAR(180) NOT NULL,
  name_kh VARCHAR(180) NULL,
  phone VARCHAR(30) NULL,
  email VARCHAR(150) NULL,
  gender ENUM('male','female','other','unknown') NOT NULL DEFAULT 'unknown',
  date_of_birth DATE NULL,
  address VARCHAR(500) NULL,
  customer_type ENUM('regular','vip','staff','partner') NOT NULL DEFAULT 'regular',
  default_discount_percent DECIMAL(7,4) NOT NULL DEFAULT 0,
  loyalty_points DECIMAL(14,2) NOT NULL DEFAULT 0,
  credit_limit DECIMAL(14,2) NOT NULL DEFAULT 0,
  current_balance DECIMAL(14,2) NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_customers_code (code),
  UNIQUE KEY uk_customers_phone (phone),
  CONSTRAINT chk_customers_default_discount CHECK (default_discount_percent >= 0 AND default_discount_percent <= 100)
) ENGINE=InnoDB;

CREATE TABLE reservations (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  branch_id BIGINT UNSIGNED NOT NULL,
  customer_id BIGINT UNSIGNED NULL,
  table_id BIGINT UNSIGNED NULL,
  reservation_no VARCHAR(50) NOT NULL,
  guest_name VARCHAR(180) NOT NULL,
  guest_phone VARCHAR(30) NOT NULL,
  guest_count SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  reservation_at DATETIME NOT NULL,
  duration_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 90,
  deposit_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  status ENUM('pending','confirmed','seated','completed','cancelled','no_show') NOT NULL DEFAULT 'pending',
  notes TEXT NULL,
  checked_in_at DATETIME NULL,
  checked_in_by BIGINT UNSIGNED NULL,
  completed_at DATETIME NULL,
  completed_by BIGINT UNSIGNED NULL,
  cancelled_at DATETIME NULL,
  cancelled_by BIGINT UNSIGNED NULL,
  created_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_reservations_branch_no (branch_id, reservation_no),
  KEY idx_reservations_schedule (branch_id, reservation_at, status),
  KEY idx_reservations_table_status (table_id, status, reservation_at),
  CONSTRAINT fk_reservations_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE RESTRICT,
  CONSTRAINT fk_reservations_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
  CONSTRAINT fk_reservations_table FOREIGN KEY (table_id) REFERENCES restaurant_tables(id) ON DELETE SET NULL,
  CONSTRAINT fk_reservations_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_reservations_checked_in_by FOREIGN KEY (checked_in_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_reservations_completed_by FOREIGN KEY (completed_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_reservations_cancelled_by FOREIGN KEY (cancelled_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
