USE restaurant_management;

CREATE TABLE orders (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  branch_id BIGINT UNSIGNED NOT NULL,
  table_id BIGINT UNSIGNED NULL,
  customer_id BIGINT UNSIGNED NULL,
  reservation_id BIGINT UNSIGNED NULL,
  order_no VARCHAR(50) NOT NULL,
  order_type ENUM('dine_in','takeaway','delivery') NOT NULL DEFAULT 'dine_in',
  status ENUM('draft','open','sent_to_kitchen','preparing','ready','served','partially_paid','paid','cancelled','voided') NOT NULL DEFAULT 'open',
  guest_count SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  subtotal DECIMAL(14,2) NOT NULL DEFAULT 0,
  discount_type ENUM('none','percent','fixed') NOT NULL DEFAULT 'none',
  discount_value DECIMAL(14,4) NOT NULL DEFAULT 0,
  discount_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  discount_reason VARCHAR(255) NULL,
  discount_applied_by BIGINT UNSIGNED NULL,
  discount_applied_at DATETIME NULL,
  service_charge_rate DECIMAL(7,4) NOT NULL DEFAULT 0,
  service_charge_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  tax_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  rounding_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  total_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  paid_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  balance_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  notes TEXT NULL,
  opened_by BIGINT UNSIGNED NOT NULL,
  closed_by BIGINT UNSIGNED NULL,
  opened_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  closed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_orders_branch_no (branch_id, order_no),
  KEY idx_orders_branch_status_date (branch_id, status, opened_at),
  KEY idx_orders_table_status (table_id, status),
  KEY idx_orders_customer (customer_id, opened_at),
  KEY idx_orders_discount_applied_by (discount_applied_by),
  CONSTRAINT fk_orders_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE RESTRICT,
  CONSTRAINT fk_orders_table FOREIGN KEY (table_id) REFERENCES restaurant_tables(id) ON DELETE SET NULL,
  CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
  CONSTRAINT fk_orders_reservation FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE SET NULL,
  CONSTRAINT fk_orders_opened_by FOREIGN KEY (opened_by) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_orders_closed_by FOREIGN KEY (closed_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_orders_discount_applied_by FOREIGN KEY (discount_applied_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE order_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT UNSIGNED NOT NULL,
  menu_item_id BIGINT UNSIGNED NOT NULL,
  kitchen_station_id BIGINT UNSIGNED NULL,
  parent_item_id BIGINT UNSIGNED NULL,
  submission_key VARCHAR(100) NULL,
  submission_line INT UNSIGNED NULL,
  item_name VARCHAR(180) NOT NULL,
  item_name_kh VARCHAR(180) NULL,
  quantity DECIMAL(12,3) NOT NULL,
  unit_price DECIMAL(14,2) NOT NULL,
  unit_cost DECIMAL(14,4) NOT NULL DEFAULT 0,
  discount_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  tax_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  line_total DECIMAL(14,2) NOT NULL,
  kitchen_status ENUM('pending','sent','preparing','ready','served','cancelled') NOT NULL DEFAULT 'pending',
  course_no SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  notes VARCHAR(500) NULL,
  sent_at DATETIME NULL,
  ready_at DATETIME NULL,
  served_at DATETIME NULL,
  cancelled_at DATETIME NULL,
  cancelled_by BIGINT UNSIGNED NULL,
  cancellation_reason VARCHAR(500) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_order_submission_line (order_id, submission_key, submission_line),
  KEY idx_order_items_kitchen (kitchen_station_id, kitchen_status, sent_at),
  CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_order_items_menu FOREIGN KEY (menu_item_id) REFERENCES menu_items(id) ON DELETE RESTRICT,
  CONSTRAINT fk_order_items_station FOREIGN KEY (kitchen_station_id) REFERENCES kitchen_stations(id) ON DELETE SET NULL,
  CONSTRAINT fk_order_items_parent FOREIGN KEY (parent_item_id) REFERENCES order_items(id) ON DELETE SET NULL,
  CONSTRAINT fk_order_items_cancel_user FOREIGN KEY (cancelled_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE order_item_modifiers (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  order_item_id BIGINT UNSIGNED NOT NULL,
  modifier_name VARCHAR(150) NOT NULL,
  quantity DECIMAL(12,3) NOT NULL DEFAULT 1,
  unit_price DECIMAL(14,2) NOT NULL DEFAULT 0,
  line_total DECIMAL(14,2) NOT NULL DEFAULT 0,
  CONSTRAINT fk_order_modifiers_item FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE kitchen_tickets (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  branch_id BIGINT UNSIGNED NOT NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  kitchen_station_id BIGINT UNSIGNED NOT NULL,
  ticket_no VARCHAR(50) NOT NULL,
  sequence_no INT UNSIGNED NOT NULL DEFAULT 1,
  status ENUM('new','accepted','preparing','ready','completed','cancelled') NOT NULL DEFAULT 'new',
  sent_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  accepted_at DATETIME NULL,
  ready_at DATETIME NULL,
  completed_at DATETIME NULL,
  UNIQUE KEY uk_kitchen_ticket (branch_id, ticket_no),
  KEY idx_kitchen_queue (kitchen_station_id, status, sent_at),
  CONSTRAINT fk_kitchen_tickets_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE RESTRICT,
  CONSTRAINT fk_kitchen_tickets_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_kitchen_tickets_station FOREIGN KEY (kitchen_station_id) REFERENCES kitchen_stations(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE kitchen_ticket_items (
  kitchen_ticket_id BIGINT UNSIGNED NOT NULL,
  order_item_id BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (kitchen_ticket_id, order_item_id),
  CONSTRAINT fk_ticket_items_ticket FOREIGN KEY (kitchen_ticket_id) REFERENCES kitchen_tickets(id) ON DELETE CASCADE,
  CONSTRAINT fk_ticket_items_order_item FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE table_transfers (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT UNSIGNED NOT NULL,
  from_table_id BIGINT UNSIGNED NULL,
  to_table_id BIGINT UNSIGNED NOT NULL,
  transferred_by BIGINT UNSIGNED NOT NULL,
  reason VARCHAR(500) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_table_transfers_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT,
  CONSTRAINT fk_table_transfers_from FOREIGN KEY (from_table_id) REFERENCES restaurant_tables(id) ON DELETE SET NULL,
  CONSTRAINT fk_table_transfers_to FOREIGN KEY (to_table_id) REFERENCES restaurant_tables(id) ON DELETE RESTRICT,
  CONSTRAINT fk_table_transfers_user FOREIGN KEY (transferred_by) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB;
